Repository OwenConW/Final_Proyect, pull requests merged in 2022-08, with the labels that each got.

#7 Feat(client/redux) add the basic configuration from redux, reducer, s…
  client/src/index.js
  client/src/redux/store.js
  client/src/redux/userActions.js
  client/src/redux/userSlice.js
Labels: New Feature, Pending to review

#10 modified( client/app ) test development
  client/src/App.js
Labels: Pending to review

#11 modified(client/redux) change some issues
  client/src/redux/userActions.js
Labels: I need help!

#18 Modif( client/app - index ) Configuraciones CSS
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/index.css
Labels: Pending to review, Styles

#34 Feat(client/src/component/navbar) Add Navbar component and edit app.css
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Navbar/Navbar.module.scss
  client/src/components/Navbar/assets/login.svg
  client/src/components/Navbar/assets/logo.svg
  client/src/components/Navbar/assets/userimage.jpg
  client/src/index.css
Labels: New Feature, Pending to review, Styles

#42 owen modified(api/routes) modifique en la importacion de index la imp…
  api/src/routes/index.js
Labels: Bugs Fixed

#37 feat(components/card) creacion de Card base
  client/src/components/Card/Card.jsx
  client/src/components/Card/Card.module.scss
  client/src/components/Card/assets/Det_interior.svg
  client/src/components/Card/assets/Details.svg
  client/src/components/Card/assets/Star.svg
Labels: New Feature, Pending to review, Styles

#38 feat(src/components/Login) Add Login component
  client/public/index.html
  client/src/App.js
  client/src/components/Login/Login.jsx
  client/src/components/Login/Login.module.scss
  client/src/components/Login/assets/background.svg
  client/src/components/Login/assets/logo.svg
Labels: New Feature, Styles, Dont merge

#61 Feat(components/Login) Add Auth0 to Login :)
  api/index.js
  api/src/models/User.js
  api/src/routes/verify/verify.route.js
  client/src/App.js
  client/src/components/Home/Home.jsx
  client/src/components/Loader/Loader.jsx
  client/src/components/Loader/Loader.module.css
  client/src/components/Login/Login.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Navbar/Navbar.module.scss
  client/src/components/Onboarding/Onboarding.jsx
  client/src/components/Onboarding/Onboarding.module.scss
  client/src/components/Profile/Profile.jsx
  client/src/components/localStorage.js
  client/src/index.js
  client/src/redux/userActions.js
  client/src/redux/userSlice.js
Labels: New Feature

#98 Feat(src/components/Map) Add distances on map
  api/index.js
  client/package.json
  client/src/components/Details/Details.jsx
  client/src/components/Map/AllMarkers/AllMarkers.jsx
  client/src/components/Map/AllMarkers/assets/albanil.png
  client/src/components/Map/AllMarkers/assets/carpintero.png
  client/src/components/Map/AllMarkers/assets/costurero.png
  client/src/components/Map/AllMarkers/assets/electricista.png
  client/src/components/Map/AllMarkers/assets/gasista.png
  client/src/components/Map/AllMarkers/assets/jardinero.png
  client/src/components/Map/AllMarkers/assets/pintor.png
  client/src/components/Map/AllMarkers/assets/plomero.png
  client/src/components/Map/AllMarkers/assets/programador.png
  client/src/components/Map/AllMarkers/styles.js
  client/src/components/Map/MapView.jsx
  client/src/components/Map/MapView.module.scss
  client/src/components/Map/asset/usericon.png
  client/src/components/Map/mapIcons.js
  client/src/handlers/pitagorasDistance.js
  client/src/index.css
Labels: New Feature, Bugs Fixed, Pending to review, Styles

#102 Fix(Onboarding) fixed with user model
  api/src/routes/verify/verify.route.js
  client/src/components/Details/Details.module.scss
  client/src/components/Map/MapView.jsx
  client/src/components/Map/mapIcons.js
  client/src/components/Onboarding/Onboarding.jsx
  client/src/components/Profile/Profile.module.scss
  client/src/handlers/validators.js
Labels: Bugs Fixed

#104 Termine el mapa no lo toco mas en la puta vida nashi
  api/src/functions/Functions_user.js
  client/src/components/Map/AllMarkers/AllMarkers.jsx
  client/src/components/Map/MapView.jsx
  client/src/components/Map/MapView.module.scss
Labels: New Feature, Bugs Fixed, Pending to review, Styles
